buzzing-java:
  seo:
    base-path: "/buzzing-java-landing-page/"
    canonical-url: "https://pradeepngupta.github.io/buzzing-java-landing-page/"
    og-url: "https://pradeepngupta.github.io/buzzing-java-landing-page/"
    og-image: "https://pradeepngupta.github.io/buzzing-java-landing-page/images/og-image.jpg"
    og-site-name: "https://pradeepngupta.github.io/buzzing-java-landing-page/"